# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15d471ctmRvMgI-50q5pBdJ7kfzV2g5Cs
"""

import streamlit as st

st.write("Hello World!!!")